### ISSUE TITLE
EmuDeck

### ISSUE THREAD

**Issue by rawdatafeel** [Open-Wine-Components/ULWGL#1]
Hiya! I saw this project on reddit and was interested in using it for EmuDeck.

I apologize if this is not the best place for this, but wanted to share my use-case and hear feedback. 

I was looking to use this script to launch emulators that are Windows only/do not have Linux equivalents through a script (so it can be automated). 

Specifically, I was looking at the Model 2 emulator. The idea would be to use this script, distribute a gamefix file (with the protonfixes required to run Model 2), and automate the installation/placement of the Model 2 emulator. 

There are a couple of other emulators such as BigPEmu and Cxbx-Reloaded that might be neat to automate through EmuDeck as well. 

A couple of questions:

* Since Model 2 is not a Steam game, it does not have a game ID. I can assign it one easily enough, but if there's interest in using this tool for non-Steam games as well, would it be possible to somehow "create" game IDs so we can share gamefix files for these programs/games?
* If I am interested in PR'ing and automating a Model 2 installation to EmuDeck using this tool, is that okay to do/in lines with what this tool sets out to do?

One concern that I had is that Model 2 is a pretty finicky emulator and seems to require ROMs launching from the same directory. However, if I add a `cd` into a custom script to wherever Model 2 is, ULWGL no longer works (because of `./ULWGL`). Is the best solution on my end here to "hardcode" the ULWGL path?

**Comment by GloriousEggroll** [comment]
cding into a directory should be resolved now because gamelauncher.sh calls ULWGL from its absolute path:

https://github.com/Open-Wine-Components/ULWGL-launcher/commit/062ff6798b4e244ed3a8f92c73337a8eadf598db

guidelines for creating game ids for wine games/applications such as emulators can be found here:

https://github.com/Open-Wine-Components/ULWGL-database?tab=readme-ov-file#rules-for-adding-ulwgl-id-entries

the gameids correlate with protonscripts matching those ids, which are written in python. once you create a gameid, create a matching protonfix for it (which applies any winetricks needed to the prefix that the emulator may need):
https://github.com/Open-Wine-Components/ULWGL-protonfixes

**Comment by GloriousEggroll** [comment]
closing as this should now be resolved.

Model 2 now has an entry:
https://github.com/Open-Wine-Components/ULWGL-protonfixes/blob/master/gamefixes-ulwgl/ulwgl-model2.py
https://github.com/Open-Wine-Components/ULWGL-database/blob/f588426d24c6d94081c1cf8addc627b62555d60a/ULWGL-database.csv#L19

API endpoint is available to pull it ulwgl id:
https://github.com/Open-Wine-Components/ULWGL-database/blob/main/ulwgl.openwinecomponents.org/README.md
https://ulwgl.openwinecomponents.org/ulwgl_api.php

It can be searched manually also:
https://ulwgl.openwinecomponents.org/index.php
