### ISSUE TITLE
Disable Winetricks popup warning messages?

### ISSUE THREAD

**Issue by Faugus** [Open-Wine-Components/ULWGL#114]
```
WINEPREFIX=/home/faugus/.config/faugus-launcher/prefixes/wow GAMEID=winetricks-gui  STORE="none" "/usr/bin/umu-run" ""
```

Is there a way to disable these popup warning messages?

https://drive.google.com/file/d/1EG84FcYO2hS6L7k3e1Z603VH7J3DxPOZ/view?usp=sharing

https://github.com/Open-Wine-Components/umu-launcher/assets/112667550/b58ee802-c5a1-4fa7-859f-fc84ef5f5dbf

**Comment by R1kaB3rN** [comment]
This is a problem upstream and umu has no control over this when using the winetricks GUI. 

Here are links to the relevant issues:
- https://github.com/Winetricks/winetricks/issues/2177
- https://github.com/Winetricks/winetricks/issues/2172

Also, since https://github.com/Open-Wine-Components/umu-launcher/commit/f4fb1585c6e4627f577ec80f8228f8c72bf83001 umu is able to run winetricks verbs without setting `GAMEID=winetricks-gui` , allowing clients apps to be the front end instead of zenity.

**Comment by Faugus** [comment]
@R1kaB3rN How do I run the Winetricks GUI with this new method?

```
[faugus@archlinux ~]$ WINEPREFIX=/home/faugus/.config/faugus-launcher/prefixes/world-of-warcraft GAMEID=WoW "/usr/bin/umu-run" "winetricks"
ERROR:  No winetricks verb specified
[faugus@archlinux ~]$ WINEPREFIX=/home/faugus/.config/faugus-launcher/prefixes/world-of-warcraft GAMEID=WoW "/usr/bin/umu-run" "winetricks --gui"
steamrt3 is up to date
UMU-Proton is up to date
WARNING:  Executable not found: winetricks --gui
ProtonFixes[17971] INFO: Running protonfixes
ProtonFixes[17971] INFO: Running checks
ProtonFixes[17971] INFO: All checks successful
ProtonFixes[17971] INFO: Using global defaults for UNKNOWN (WoW)
ProtonFixes[17971] INFO: No global protonfix found for UNKNOWN (WoW)
Proton: winetricks --gui
Proton: Executable is inside wine prefix, launching normally.
fsync: up and running.
Application could not be started, or no application associated with the specifie
d file.
ShellExecuteEx failed: File not found.
```

**Comment by R1kaB3rN** [comment]
The second command is incorrect usage and will result in that error because the launcher is interpreting "winetricks --gui" as an executable. Everything after the `winetricks` positional argument should be a valid winetricks verb, so `--gui` in this case would be invalid too.

Here's an example of the correct usage taken from umu(1):
`$ GAMEID=0 PROTONPATH=GE-Proton umu-run winetricks quartz wmp11 qasf`

**Comment by Faugus** [comment]
Are you planning on implementing the GUI option with this new method or should I stick with the previous `GAMEID=winetricks-gui`?

**Comment by R1kaB3rN** [comment]
No, because `--gui` isn't an official winetricks verb but a CLI option. If you want a GUI and don't want to write one, I suggest sticking with `GAMEID=winetricks-gui`.

**Comment by R1kaB3rN** [comment]
Closing as this isn't a bug in the launcher and supporting winetricks CLI options like `--gui` isn't planned.

**Comment by melroy89** [comment]
I actually found a middle ground everybody can live with. By providing the `--gui` in combination with the `-q`, that will disable this warning popup message, see my PR: https://github.com/Winetricks/winetricks/pull/2334
