### ISSUE TITLE
This is more like suggestion instead of issue - problem with GE-Proton solution is similar to umu-proton

### ISSUE THREAD

**Issue by rairay91** [Open-Wine-Components/ULWGL#133]
When i run a game with native umu-proton the launcher automatically check for update for latest umu-proton release, if there is a new release umu download it and create a link umu-latest/umu-proton whatever to that version and delete old. Now my issue is that for working with ge-proton which is more uptodate and have more patches/fixes than umu-proton, i have to manage it manually. Umu download latest version automatically at first boot but keep older version and do not create a link to the latest ge-proton just like it does to latest umu-proton.
So at the end umu should also download and create GE-Proton link to the latest downloaded GE-Proton in the same directory as it does to the latest umu-proton and should delete older version unless i assigned umu to use a specific version of proton.
Why downloading latest version of ge-proton then creating a link to that in the same directory and deleting previous version is important?
Because it eliminates the overhead of managing this manually.
And to be honest keeping older version of ge-proton is not necessary because i haven't ever noticed if we need to keep older ge-proton. Even if there is a game that need old version of ge-proton, we can do it manually.

**Comment by loathingKernel** [comment]
The basic idea is that UMU-Proton can be a stable version as close as possible to Valve's stable Proton that includes the minimum required modifications to work with umu, and as such it serves as the default version to download. On the other hand GE-Proton has a lot more patches, a lot more customization and it is more likely for a broken update to occur.

>  Because it eliminates the overhead of managing this manually.

This is all well and good if nothing breaks, but if something does break, and a user wants to test different versions, then umu should not get in their way of testing the older versions. If by default umu would update or even delete older GE-Proton versions it would only add to the confusion and the frustration of the user who is trying to identify and solve an issue.

There are other very good tools that can do what you want to do such as protonup-qt, the GUI launcher of your preference, or even your own custom update script. There is very little reason to burden umu with that functionality.

**Comment by rairay91** [comment]
Your answer seems helpfull. But i barely noticed any game that exclusive requires specific proton version. But that is okay.
However, you can do one thing. Whenever there is a new version of proton-ge downloaded by umu, umu automatically assign a link to the latest version of ge-proton with specific name like "GE-Proton", similar to how it does with umu-proton. In this situation i can specify to all or most of my games to use that proton i.e. "GE-Proton".
If you did that I don't need to do tinkering with all games to use latest version of proton-ge. I just open launcher (umu, lutris, heroic e.t.c) and start playing my games with the latest proton-ge. But previous version still exist there if any game requires that exclusively.

**Comment by alterNERDtive** [comment]
Pretty sure you can do `PROTONPATH=GE-Proton`.

**Comment by rairay91** [comment]
> Pretty sure you can do `PROTONPATH=GE-Proton`.

Amd how can i use umu in lutris? Most recent release comes with umu, but don't know how to use it. I asked in lutris discord channel and on github as well, but no help.

**Comment by alterNERDtive** [comment]
Set Wine version to `GE-Proton (Latest)` in the settings. Not sure if you still have to install umu manually first or if Lutris does it for you these days.

**Comment by R1kaB3rN** [comment]
> Your answer seems helpfull. But i barely noticed any game that exclusive requires specific proton version. But that is okay. However, you can do one thing. Whenever there is a new version of proton-ge downloaded by umu, umu automatically assign a link to the latest version of ge-proton with specific name like "GE-Proton", similar to how it does with umu-proton. 

To clarify, the `UMU-Latest` link is **not** intended for end users and it's value can change to either the latest UMU-Proton or GE-Proton build if the client is running a game that uses either of those two builds. That symbolic link is for internal use so that clients like Lutris can identify the latest Proton build being used for that game session.

Sorry, but I'm not following how assigning a link like `GE-Proton` would be useful in your case because you want to always use the latest GE-Proton _and_ have previous GE-Proton builds deleted, correct? The current behavior of `PROTONPATH=GE-Proton` satisfies the first half of your needs and you should be aware of that given the previous issue you created. However, if you want to have umu delete previous builds too, the current behavior must either change or we can implement a new behavior behind a new value such as `PROTONPATH=GE-Latest` which would delete the previous builds too.

**Comment by R1kaB3rN** [comment]
In any case though, there'll need more discussion about whether to change this behavior and will have to addressed in the next release. I do know that Lutris is supportive of changing the behavior, and that Heroic is indifferent as they have their own wine manager and only interested in the runtime. Also, umu's Proton managing system isn't compelling enough for launchers to switch unless differential Proton updates are implemented.

But I do sympathize with you because personally, I would want previous builds to be deleted. The current behavior is just currently conservative due to loathingkernel's points.

**Comment by R1kaB3rN** [comment]
> Set Wine version to `GE-Proton (Latest)` in the settings. Not sure if you still have to install umu manually first or if Lutris does it for you these days.

The dropdown option of `GE-Proton (Latest)` in the latest stable version of Lutris is misleading and deceptive as it'll use UMU-Proton instead, so Lutris users would need to set `PROTONPATH=GE-Proton` in the environment variables section to use the latest GE-Proton build. This problem should already be addressed in the latest branch of Lutris, so you can expect the correct behavior in their next stable release.

**Comment by rairay91** [comment]
> > Set Wine version to `GE-Proton (Latest)` in the settings. Not sure if you still have to install umu manually first or if Lutris does it for you these days.
> 
> The dropdown option of `GE-Proton (Latest)` in the latest stable version of Lutris is misleading and deceptive as it'll use UMU-Proton instead, so Lutris users would need to set `PROTONPATH=GE-Proton` in the environment variables section to use the latest GE-Proton build. This problem should already be addressed in the latest branch of Lutris, so you can expect the correct behavior in their next stable release.

That is why i was asking the devs that umu should create a symbolic link to latest doenloaded ge-proton similar to how it does with latest downloaded umu-proton. All they need to do is add couple of more lines in umu_proton.py.

**Comment by rairay91** [comment]
> > Set Wine version to `GE-Proton (Latest)` in the settings. Not sure if you still have to install umu manually first or if Lutris does it for you these days.
> 
> The dropdown option of `GE-Proton (Latest)` in the latest stable version of Lutris is misleading and deceptive as it'll use UMU-Proton instead, so Lutris users would need to set `PROTONPATH=GE-Proton` in the environment variables section to use the latest GE-Proton build. This problem should already be addressed in the latest branch of Lutris, so you can expect the correct behavior in their next stable release.

That is why i was asking the devs that umu should create a symbolic link to latest doenloaded ge-proton similar to how it does with latest downloaded umu-proton. All they need to do is add couple of more lines in umu_proton.py. How umu create a symbolic link to latest umu proton but not create for latest ge proton is more confusing.

**Comment by R1kaB3rN** [comment]
Closing because given your needs you don't need a symbolic link to the latest GE-Proton to use it and you need not concern yourself with it as it's not for you. `PROTONPATH=GE-Proton` should suffice for your use case to use the latest GE-Proton, which should prevent the need from having you managing anything or specify paths besides deleting the old GE-Proton builds. 

Applying differential updates will be explored in the future, which is how the Steam client does updates, to allow for efficient updates. In such a system, there'll only be one GE-Proton/UMU-Proton directory. Though if you're not happy with the current system in umu, I suggest that you please do not use it for now. Or alternatively, make a pull request that's improves the current system and can handle the above concerns.
