### ISSUE TITLE
Initialization of wineprefix before running game

### ISSUE THREAD

**Issue by sewnie** [Open-Wine-Components/ULWGL#14]
Hi. i'm here to ask on how to utilize ULWGL's `wineboot` application to initialize a wineprefix in my Roblox bootstrapper for linux Vinegar.

We have a wineprefix initialization routine, for which the Player runs `wineboot -i`, but Studio uses a `regedit` command (which inherently initializes the wineprefix if not present) to set the DPI of 97:
https://github.com/vinegarhq/vinegar/blob/master/cmd/vinegar/binary.go#L163-L171

Is it possible to run `wineboot` via `gamelauncher.sh` like normal? `gamelauncher.sh wineboot -i`? or is there something else?

Roblox studio cannot run on the default DPI 96, this is linked to WineHQ bug report [52189](https://bugs.winehq.org/show_bug.cgi?id=52189) and [55666](https://bugs.winehq.org/show_bug.cgi?id=55666), which were unnoticed by Wine maintainers. I'm not quite sure about the details, but it may be related to EnableNonClientDpiScaling. It would be greatly appreciated if it was possible to get this implemented and fixed in Wine.

**Comment by loathingKernel** [comment]
> Is it possible to run wineboot via gamelauncher.sh like normal? gamelauncher.sh wineboot -i? or is there something else?

Take a look here as a possible way to do that https://github.com/Open-Wine-Components/ULWGL-launcher/pull/8#issuecomment-1925301289 . You might need to pay some extra attention to the `PROTON_VERB` you should use.

**Comment by sewnie** [comment]
I appreciate your help, but i don't understand the linked comment. Are you referring to `PROTON_VERB="createprefix"`?

Additionally, Vinegar will use `wineboot` to kill the wineprefix.

**Comment by loathingKernel** [comment]
>  Are you referring to PROTON_VERB="createprefix"

Partially yes, that's one way to do it.

I referred you to that comment because that's is my use-case of using wine's binaries, as an example. `PROTON_VERB` takes the following values `run`, `runinprefix`, `waitforexitandrun` and `getnativepath`/`getcompatpath` (there is also `destroyprefix`). I was talking about the `runinprefix` verb, because that's the one that will execute something in an already active prefix ([proton code](https://github.com/ValveSoftware/Proton/blob/proton_8.0/proton#L1737)). So if you want to run something while `wineserver` is active without waiting for it to exit first, you need to use the `runinprefix` verb.

Edit: As far as I know, Steam uses the `run` verb to setup the prefix, for which it then waits to exit with `waitforexitandrun` before running the application with the same verb. This might not be applicable to ULWGL though.

**Comment by imLinguin** [comment]
> Is it possible to run wineboot via gamelauncher.sh like normal? gamelauncher.sh wineboot -i? or is there something else?

Yes it's possible, if you want to avoid triggering protonfixes in that moment make sure to use `PROTON_VERB=run`. Everything should work as wineboot is a normal executable available from windows environment. It may not work with the current GE-Proton, however you can try with [ULWGL-Proton](https://github.com/Open-Wine-Components/ULWGL-proton) build

**Comment by sewnie** [comment]
I can't: #13

**Comment by sewnie** [comment]
What is the difference between `destroyprefix` and simply removing `$WINEPREFIX`?

**Comment by GloriousEggroll** [comment]
```
Is it possible to run wineboot via gamelauncher.sh like normal? gamelauncher.sh wineboot -i? or is there something else?
```
send  `createprefix` as the executable. Also if the prefix does not exist and you send 'regedit' it will still be automatically created by ULWGL + proton

**Comment by imLinguin** [comment]
> So if you want to run something while wineserver is active without waiting for it to exit first, you need to use the runinprefix verb.

`runinprefix` should only be ran on already setup prefix (as it also skips some validity checks). So unless caller knows what they are doing, only `run` and `waitforexitandrun` should be used.

**Comment by loathingKernel** [comment]
> > So if you want to run something while wineserver is active without waiting for it to exit first, you need to use the runinprefix verb.
> 
> `runinprefix` should only be ran on already setup prefix (as it also skips some validity checks). So unless caller knows what they are doing, only `run` and `waitforexitandrun` should be used.

I believe it would be bad to start modifying an active prefix, and `runinprefix` skips that, that's why I mentioned that it should be used if `wineserver` is already active (also implying the prefix is already set up). This was intended as the proper way of using executing `wineboot -s` or `wineboot -k` to stop the prefix as asked here https://github.com/Open-Wine-Components/ULWGL-launcher/issues/14#issuecomment-1927428046.

**Comment by GloriousEggroll** [comment]
closing as this has been answered
