### ISSUE TITLE
Xlib.error.DisplayConnectionError: Can't connect to display ':1': [Errno 111] Connection refused

### ISSUE THREAD

**Issue by R1kaB3rN** [Open-Wine-Components/ULWGL#145]
Using the NixOS package, it seems like the launcher somehow retrieves the gamescope base layer order sequence from `DISPLAY=:0` which would cause the launcher to raise an exception when trying to connect to `DISPLAY=:1`. This is unexpected as we only try to connect to `DISPLAY=:1` when using gamescope. Though, this isn't critical as umu handles the exception and it appears users can still run their games.

See https://github.com/Open-Wine-Components/umu-launcher/issues/142#issuecomment-2221598386 for the traceback.

**Comment by bohanubis** [comment]
@R1kaB3rN I found a way to reproduce this at least on nixos
basically
open steam big picture mode (I am writing this while only testing with steam flatpak I will check with native package after rebooting)
run umu
wow DISPLAY is wrong

**Comment by bohanubis** [comment]
yeah this happens using native steam package on nix
or flatpak steam
and umu is affected somehow

**Comment by R1kaB3rN** [comment]
Thanks for confirming this. 

Do you mind running a game after building umu with [this branch](https://github.com/Open-Wine-Components/umu-launcher/tree/display-err)? While it doesn't solve the puzzle of why a gamescope base layer order sequence was retrieved, in that branch, at least umu handles the display error properly when trying to connect to any display.

**Comment by bohanubis** [comment]
@R1kaB3rN so that fixes nothing
![image](https://github.com/user-attachments/assets/64f5f443-e42b-49a6-a024-36406cf40b8f)

I will try to debug the issue cause why not
anyway at least we know that steam is the one responsible for this
also
@R1kaB3rN can you reproduce the issue using big picture mode ??

**Comment by bohanubis** [comment]
I added a log here: https://github.com/beh-10257/umu_nix/commit/2677388012bcff3803beb8149e48a9d91673e348
and when I actually run umu inside gamescope that log doesn't show up but after doing the whole steam thingy it works lol

**Comment by bohanubis** [comment]
it shows this when I actually run umu using gamescope
```DEBUG [umu_run.get_gamescope_baselayer_order:524]:GAMESCOPECTRL_BASELAYER_APPID property not found```

**Comment by FeyrisTan** [comment]
I've been having this issue as well. Happens with Wayland - x11 is fine:
`Can't connect to display ":0": b'Authorization required, but no authorization protocol specified`

so running echo $DISPLAY returns 1 instead of 0.
in: /usr/lib/python3.12/site-packages/umu/umu_run.py
changing line 511 from `d = display.Display(":0")`  to `d = display.Display(":1")`  works

**Comment by R1kaB3rN** [comment]
> I've been having this issue as well. Happens with Wayland - x11 is fine: `Can't connect to display ":0": b'Authorization required, but no authorization protocol specified`
> 
> so running echo $DISPLAY returns 1 instead of 0. in: /usr/lib/python3.12/site-packages/umu/umu_run.py changing line 511 from `d = display.Display(":0")` to `d = display.Display(":1")` works

The exception that was raised in your case is different than the one I had mentioned in this issue. Please make a different issue for it if you're still experiencing that problem.
