### ISSUE TITLE
tried installing with gdebi package installer.

### ISSUE THREAD

**Issue by DOOMMARINE117** [Open-Wine-Components/ULWGL#203]
it gaved me an error when installing it.  dependency is not satisfied. python3-xiib.

**Comment by R1kaB3rN** [comment]
Sorry, but am I to assume you are on a Debian-like Linux distribution? The associated workflow for building .deb package passes in our CI, and it doesn't help that you are not providing enough context to refute it.

Please review the repository's instructions for building the .deb package. Otherwise, please look into a [user install](https://github.com/Open-Wine-Components/umu-launcher?tab=readme-ov-file#installing-as-user) or [building the Flatpak](https://github.com/Open-Wine-Components/umu-launcher/tree/main/packaging/flatpak).
