### ISSUE TITLE
here is my full issue of trying to install on debian. 

### ISSUE THREAD

**Issue by DOOMMARINE117** [Open-Wine-Components/ULWGL#216]
sudo apt install /home/talion117/Downloads/MSC/python3-umu-launcher_1.1.1-1_all.deb
[sudo] password for talion117: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'python3-umu-launcher' instead of '/home/talion117/Downloads/MSC/python3-umu-launcher_1.1.1-1_all.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-umu-launcher : Depends: python3-xlib (>= 0.33) but 0.29-1 is to be installed
                        Depends: python3-filelock (>= 3.13.1) but 3.6.0-1 is to be installed
E: Unable to correct problems, you have held broken packages.

i have those two installed now. but it still says those.

**Comment by hihanhoesj** [comment]
The issue is that although you have the packages installed the versions you have installed is not new enough.

Guessing by the versions you have installed, you are running on Debian 12.

The published packages, it would seem, has been built on an Ubuntu 24.04 and without "frankendebianing" this you will have to compile UMU from scratch.

I am in the same boat unfortunately.

Edit: I see 1.1.2 has been released that fixes our problem. Thank you team
