### ISSUE TITLE
[Question] how does this replace Wine-GE-Proton? and can this run applications as well?

### ISSUE THREAD

**Issue by XDM-Inc** [Open-Wine-Components/ULWGL#228]
So i usually use Wine-GE-Proton for unorthodox apps or testing of windows apps on linux. sometimes a app may just not work so well in stock wine so i use separated wines to launch them. example, im dealing with a windows app that will hard lock on stock wine due to the unimplemented feature of VK-Child window. so i run it with wine-tkg. that gets around that issue but has other issues like flickering UI and so id like to test with other versions of wine. Wine-GE-Proton was my go to for most troublesome apps but now the last version is almost a year as its "depreciated" in favor for umu. so in short, i as wondering how does this umu hold up as a 100% replacement of Wine-GE-Proton? looking at the instructions for it it seems a but roundabout and confusing to me that is but also seems to be mainly geared towards games. how well is it for applications as well?

**Comment by GloriousEggroll** [comment]
wine-ge was always built for games, it's a direct copy of proton-ge, just without the steamclient bits.

the problem with wine-ge is that it relies on the libraries installed on the user's system. Depending on what OS, these library versions can break or be completely missing.

when steam runs proton or proton-ge, it uses a special container software called pressure-vessel. This software runs a container using the steam linux runtime -- which is a full set of libraries specifically built for proton. This resolves the issue you get when running wine-ge or any other native version of wine, because it's being run inside a container with the same libraries no matter what system it's on. Within the container, proton-ge runs and subsequently it runs your games. This action is what umu-launcher replicates. It does the same thing outside of steam.

umu itself is not really meant to be a standalone tool for end users. It's a CLI (command line interface) tool meant to be used by other applications such as lutris or heroic. Those applications provide easy to use interfaces for users.

I have no idea on how useful it is for non-game applications. It was never designed for that.

**Comment by XDM-Inc** [comment]
ok,thanks for the info. i guess i can just continue modifying proton GE when needed. it mostly works with very little hitches.
