### ISSUE TITLE
EA App when using Z drive, has almost no capacity

### ISSUE THREAD

**Issue by LethalManBoob** [Open-Wine-Components/ULWGL#232]
edit: image removed for privacy reasons
EA App installed to C Drive as the default. Done via heroic
this works fine if disabling umu runtime with proton

**Comment by GloriousEggroll** [comment]
@imLinguin tagging.

Run with PROTON_SET_GAME_DRIVE=1

**Comment by LethalManBoob** [comment]
> @imLinguin tagging.
> 
> Run with PROTON_SET_GAME_DRIVE=1

That did not solve the issue
edit: It created an S drive, this works just fine
maybe this should be set as default or the command should be present on the github page as a troubleshooting step, i dont want this knowledge to be hidden

**Comment by GloriousEggroll** [comment]
> > @imLinguin tagging.
> > Run with PROTON_SET_GAME_DRIVE=1
> 
> That did not solve the issue edit: It created an S drive, this works just fine maybe this should be set as default or the command should be present on the github page as a troubleshooting step, i dont want this knowledge to be hidden

the only reason i mentioned it is because I had a discussion over the weekend with Linguin about heroic possibly needing this set, he said it wasnt needed because they set the install location for umu inside the prefix -- and then of course your bug came up which does not follow that statement. We already advised Junk Store that they should permanently set this in their client as well.

**Comment by imLinguin** [comment]
@LethalManBoob could you attach a log of this game entry from Heroic?

**Comment by GloriousEggroll** [comment]
resolved in GE-Proton (and soon UMU-Proton):

https://github.com/GloriousEggroll/proton-ge-custom/commit/541689054a7b44e75e07d2dee8a563551c70bca0

We can't do anything about the Z: drive, it has to be there for unix paths to work, and it's read-only due to the container. What we did is instead check if any of these exist and are not empty:
/mnt, /run/media, /media, <user home>
and if so, mount them as writable drives in the prefix.
