### ISSUE TITLE
nothing launches after update on Lutris

### ISSUE THREAD

**Issue by efwis** [Open-Wine-Components/ULWGL#233]
Started playing a game on Lutris. After latest umu-launcher update i get he following error in lutris log for game. This is an issue on any game that relies on the proton in lutris.

please let me know what else you might need, I am including the log from lutris so you can see the output.

system specs:

EndeavourOS
Linux 6.11.3-arch1-1
Hyprland
Lenovo Ideapad 5 15ABA7
AMD Ryzen 7 5825U
AMD Barcelo Integrated GPU
16GB Ram
[backtrace.txt](https://github.com/user-attachments/files/17370900/backtrace.txt)

**Comment by GloriousEggroll** [comment]
backtrace doesnt tell us anything other than that the game crashed. also please open the bug on lutris's side. additionally, please indicate which version of lutris you are using in the lutris side bug. current lutris release has a lot of problems with umu that have been pretty much all fixed in upstream git.
