### ISSUE TITLE
Screen Goes to Sleep While Playing Windows Games with Controller Outside of Steam – UMU Launcher

### ISSUE THREAD

**Issue by RaulKong898** [Open-Wine-Components/ULWGL#262]
I encountered an issue with inactivity detection while playing Windows games on Linux using a controller. Regardless of the method used to run Windows games (UMU Launcher, Bottles, or other emulation applications), my system considers me inactive, causing the screen to go to sleep automatically. This issue does not occur when I play games through Steam.

This is frustrating, especially in online games, where interruptions can affect progress and lead to penalties. I hope that UMU Launcher could help address this issue, allowing controller activity to be properly detected on Linux outside of Steam.

Thank you in advance, and I look forward to a solution!

**Comment by R1kaB3rN** [comment]
It’s questionable whether making sure the computer will not fall asleep is something we should support, and I would argue it’s a client responsibility and outsides our scope. umu-launcher is not a client, but a backend application currently used to run games through Proton. Our tool specifically follows closely Steam’s command line execution and its required environment configuration that enables running games through Proton (but with some additions), and no where in that command line chain or in its Steam Runtime code does it try to ensure the system will not fall asleep. Therefore, because Steam tools does not do it and that feature is irrelevant to directly running games, expanding its role solve that issue doesn’t quite make sense and it would be more appropriate to request this feature from your launcher.

**Comment by R1kaB3rN** [comment]
Closing as 'wontfix'. Though, if a Steam Input solution is ever implemented, then it's possible that this problem may be resolved as a side effect. See https://github.com/Open-Wine-Components/umu-launcher/issues/117
