### ISSUE TITLE
Missing auto download of proton in python rewrite

### ISSUE THREAD

**Issue by Amanse** [Open-Wine-Components/ULWGL#29]
The python version doesn't automatically download proton when PROTONPATH is missing like in the old bash version, ulwgl-run-cli file still exists but is not executed automatically

**Comment by loathingKernel** [comment]
That is the intended behavior so far if you are not using the flatpak. You can use `ulwgl-run-cli` if you want the automatic download. The flatpak installs `ulwgl-run-cli` as `ulwgl-run` so it is transparent in that case.

**Comment by Amanse** [comment]
ah, that's cool

**Comment by GloriousEggroll** [comment]
err, a bit of a correction -- we want ULWGL-Proton to get downloaded still regardless of flatpak or normal. its ULWGL itself we dont want updated automatically. The reason is in case they dont have any default proton version installed or selected we want to default to ULWGL-Proton rather than valve's for the protonfixes. @R1kaB3rN  on this. 

Again to clarify -- we -do- want ULWGL-Proton to automatically download in case no Proton version is specified, regardless of flatpak or normal. We -do not- want to auto-update ULWGL itself.

**Comment by Amanse** [comment]
Thanks! I thought that auto downloading proton was great and missed it, glad to see it will be back
