### ISSUE TITLE
Packaging ULWGL-launcher

### ISSUE THREAD

**Issue by loathingKernel** [Open-Wine-Components/ULWGL#45]
I made a preliminary package viewable here <https://github.com/loathingKernel/PKGBUILDs/tree/master/public/ulwgl-launcher>, I have not uploaded it yet on AUR, cause I want the OK before doing so.

Some observations from a packaging point of view.

1. A command line argument to download/update the user-local directories could be useful without requiring to run a game.
2. I went with `ulwgl-launcher` because it is the name of the repository. If it is named `ulwgl-runner` it might look like it is not associated with this project and cause confusion (for example it might look as another project using simply using `ulwgl`). If you prefer to use `-runner` for the repo too, now might be a good opportunity to rename it.
3. The project is missing a license for its own code, it might be good to add one now that steam runtime is not part of it.
4. I decided to build `reaper` and replace it in `ULWGL` in the PKGBUILD solely because I could. This can change if we don't want it, although since it is executed in the host, we can instruct packagers to rebuild it.
5. Thinking of how other distributions might package it, we should not hardcode the path to `/usr/share/ULWGL`, since we can depend on the location of the `ulwgl_run.py` script. NixOS comes to mind although I am not terribly familiar with it.
6. In the same vein as the above, some packagers might elect to use a script like the following instead of symlinking `ulwgl_run.py` to `/usr/bin`
    ```sh
    #!/usr/bin/env bash
    /usr/share/ULWGL/ulwgl_run.py "$@"
    ```
    which leads to the `exe` name in usage message to be `ulwgl_run.py`. Otherwise it works the same.
7. Let's remove the stray symlink `ULWGL/ulwgl-run`, someone is going to try and execute that without noticing it is broken. Packages can create that and and point it in the location they have `ULWGL` installed.
8. A little unrelated, maybe I should open a different issue for this. Is it possible for the steam runtime be not only downloaded but also extracted in `/tmp` before being copied? It should avoid unnecessary writes on disk, and be a bit faster.

**Comment by GloriousEggroll** [comment]
pasting here per internal discussions:


TODO:
- create a meson script or makefile that uses INSTALL_PATH and inserts them into the ulwgl-run bash scripts, this way /usr/share/ isn't a hard coded path

DONE - remove the parent check:
https://discord.com/channels/1180223017821950126/1180223019801661562/1212088165628649513

DONE - use a basic bash script for /usr/bin/ulwgl-run and ULWGL-Runner/ulwgl-run instead of a symlink so that `Path(__file__).parent` works

DONE - rename ULWGL-Runner to ULWGL-Launcher

DONE - and that should cover it other than the gpl license

DONE - also I can adjust the runtime installer bits so that it extracts to tmp

we can worry about adding updater cli commands later, id like to get those main points done first so we can get to packaging

**Comment by R1kaB3rN** [comment]
I agree with having a Makefile for packaging. 

Also, about your 5th and 6th point, the bug to correctly refer to the ulwgl-run's parent is fixed in https://github.com/Open-Wine-Components/ULWGL-launcher/pull/46/commits/e7fc14aa4b1aaaf43412787cc704bab78337bf18. Therefore, we should be able to safely remove the requirement of external shell scripts as well as the ulwgl-run symbolic link from the repo

As a result, packagers are held fully responsible for creating the appropriate link to the directory containing our files, are free to install in their own fashion, and the link files created for our directories in ~/.local/share will be created dynamically by the launcher

**Comment by R1kaB3rN** [comment]
Closing since the Makefile has been merged since https://github.com/Open-Wine-Components/ULWGL-launcher/commit/697173a2f27f0ca4f22fd09366a476593204c2fe
