### ISSUE TITLE
Improve the "out of the box" user experience by installing a desktop entry for ULWGL

### ISSUE THREAD

**Issue by Aqa-Ib** [Open-Wine-Components/ULWGL#64]
We could vastly improve the out of the box user experience by just installing a .desktop entry file for ULWGL. 
With it, users would just need to double click the game executable using their preferred file manager and the game luckily will just run, like in MS Windows. These days, fortunately, a lot of games work just by executing the .exe file without needing any fix.

Cheers !

**Comment by R1kaB3rN** [comment]
While ULWGL can be used as a standalone launcher and does support that usage to some extent, its audience and its original intention is to be used as a backend component for other GUI clients (e.g., Lutris) to make Proton accessible and to standardize configuring WINE prefixes for games. Therefore, support for mainlining the creation of .desktop entry files to improve the experience would be outside this project's scope.

And even if it were, I really think that feature should be delivered by GUI clients or at least as a 3rd party plugin outside the launcher instead as a core component

**Comment by R1kaB3rN** [comment]
However, I'm observing more cases where people use ULWGL outside it's intention and I do sympathize with using it directly. So, what I could do is make ULWGL extensible by defining a plugin interface to conform to that would allow users to write their own modules/execute their own scripts.

Like for example the launcher would read a plugins directory in `.local/share/ULWGL` and try to import the modules or execute scripts there before trying to run the game. In your case, your plugin that you or someone else wrote would create a .desktop entry after each run.

However, everyone would need to be onboard with this and this needs to be really useful to warrant it. Currently, the main priority is on stabilizing the launcher.

**Comment by Aqa-Ib** [comment]
Let me explain myself again, please.

What I mean is creating a desktop entry for ulwgl-run itself, for it to be executed directly from a file manager like GNOME Files or KDE Dolphin when double clicking a game executable.

```
[Desktop Entry]
Type=Application
Name=Run game (ULWGL)
MimeType=application/vnd.microsoft.portable-executable;application/x-ms-dos-executable;application/x-msi;application/x-ms-shortcut;application/x-bat;application/x-mswinurl;application/x-msdownload
NoDisplay=true
StartupNotify=true
Exec=env GAMEID=0 ulwgl-run %f 
```

Please, consider adding this. It would help so many people.

**Comment by Aqa-Ib** [comment]
[ Offtopic ]
> While ULWGL can be used as a standalone launcher and does support that usage to some extent, its audience and its original intention is to be used as a backend component for other GUI clients (e.g., Lutris) to make Proton accessible

If this is the case, I would like to try to make you people reconsider what ULWGL means for the FOSS community. A Unified Linux Wine Game Launcher. An accessible fork of Proton, for people to use the same way as they use Wine, but with the convenience that Proton brings for games. If GUIs use ULWGL as a backend, it is because of the same reason why GUIs use Wine as their backend, because it can launch Windows Games by itself. 

ULWGL is just the tool that we have to run Proton outside of Steam.

I think it should be a intention of the project to let people use it standalone like we use Wine.

Keep it simple !

[ /Offtopic ]

That said, **thank you** for the work, it is greatly appreciated. I just wish the best for this project and the Linux Gaming community as a whole.

**Comment by loathingKernel** [comment]
I do agree with @R1kaB3rN that this is getting slightly out of scope, and it creates a precedent to similar requests. Getting this into the project opens the possibility for requests to `dmenu` integration for example, which is arguably on the edge of scope. A similar situation happened with DXVK where people were modifying the install script to fit their peculiar needs causing unnecessary maintenance burden, resulting to it being removed eventually.

> Please, consider adding this. It would help so many people.

So far there isn't anything to suggest that it would be very useful, and it can cause confusion. The desktop file itself could be documented in the Readme, as an option instead of including it in the source, along with the constraints it entails, like hardcoding the `GAMEID` to `0`. As @R1kaB3rN said this is a better fit for the various game launchers to implement, as they can provide the correct `GAMEID`

**Comment by Aqa-Ib** [comment]
> this is a better fit for the various game launchers to implement, as they can provide the correct GAMEID.

Like Wine can be used without winetricks, ULWGL could be used without protonfixes. There are plenty of games that just run out of the box without fixes, and as time passes there will be even more. Reconsider not making ULWGL a backend project for GUIs please. Let it be just an accessible version of Proton with the same use scope as WINE but for games.

**Comment by loathingKernel** [comment]
You can already use it from the command line just like you do with Wine. I don't see any difference here from what is the usual way to use Wine.

**Comment by Aqa-Ib** [comment]
The difference is the topic of this issue. WINE has a desktop entry. ULWGL does not at the moment.

**Comment by loathingKernel** [comment]
Nobody uses or should use Wine from the desktop entry, they are missing key features that help games run better, like separate prefixes, env variables that need to be set, etc. If nothing else, this kind of Wine usage promotes bad practices as far as games are concerned and it is better to leave it as something that the user can do themselves to align it with their own requirements.

**Comment by Aqa-Ib** [comment]
I completely disagree with you.

It is a fact that there are thousands of games that can be run just by double clicking an executable from a file manager with the help of ULWGL. But instead of giving that freedom, you are basically telling the user: "Don't do it!, instead go and study how to make a desktop entry, the command line interface, or a bloated GUI to run it." I don't agree with your opinion. There are people that don't have the knowledge. Give them the freedom to just double click the executable please, just as WINE gives.

**Comment by loathingKernel** [comment]
> There are people that don't have the knowledge. Give them the freedom to just double click the executable please, just as WINE gives.

These people most likely already use a launcher for a few reasons. Linux gaming at this time is not an out of the box experience. It requires DXVK, VKD3D-proton and other such software, which they either installed themselves, which renders the lack of knowledge a moot point, or they have a launcher to handle all that for them already, in which case it renders the request not really useful. I understand that this is your preferred way of using Wine, but there is nothing to indicate that it is common.

In any case, what you are suggesting, if it is to be implemented correctly to allow non-knowledgeable users to have a good experience to the standards you are describing, it is a very thin client on top of ULWGL, which makes it even more out of scope, and ultimately a separate project in my opinion.

**Comment by mozo78** [comment]
> Linux gaming at this time is not an out of the box experience. It requires DXVK, VKD3D-proton and other such software

There are native games you know...

**Comment by loathingKernel** [comment]
> There are native games you know...

ULWGL doesn't target native games, and as such that's irrelevant, you know...

**Comment by Aqa-Ib** [comment]
> Linux gaming at this time is not an out of the box experience.  It requires DXVK, VKD3D-proton and other such software, which they either installed themselves, which renders the lack of knowledge a moot point.

That is not anymore the case with ULWGL. With it, the experience is out of the box for thousands of games, as it already includes DXVK and VKD3D-proton in its wine prefix by default.

>  they have a launcher to handle all that for them already, in which case it renders the request not really useful.

ULWGL is a Launcher itself. You are referring to GUIs. For the particular case where the user already owns a folder with the game files, GUIs are not needed for double clicking an executable, and for such case they are just bloat.

>  I understand that this is your preferred way of using Wine, but there is nothing to indicate that it is common.

People are used to MS Windows. If you want people to use Linux for gaming, give them a similar experience. In Windows when you already own a folder with the game files, you just double click the executable, or create a shortcut to it. That's it. The most common workflow for the past 40 years. 

> if it is to be implemented correctly to allow non-knowledgeable users to have a good experience to the standards you are describing, it is a very thin client on top of ULWGL, which makes it even more out of scope, and ultimately a separate project in my opinion.

No man, just make a desktop entry like WINE does, and the problem will just be solved. Thousands of games launchable out of the box just double clicking an executable from a file manager. That is a step in the right direction for people to start using Linux instead of Windows for gaming.

**Comment by Aqa-Ib** [comment]
I have already run many games with ULWGL just by double clicking them with no problems at all. It is a blessing.

 I think that this would be a blessing for a lot of people too. A huge step in Linux gaming.

Just give the users the means to try to run a game by simple double clicking. If it doesn't work, the user can go ahead and use the command line interface or a GUI instead. 

I can't think of any good reason to not give the people this blessed desktop entry for them to enjoy.

**Comment by GloriousEggroll** [comment]
Ulwgl isn't meant as a standalone tool. It should not be responsible for managing desktop shortcuts. That responsibility falls to the launchers using it

**Comment by Aqa-Ib** [comment]
We are talking about a single desktop entry for ULWGL itself, for launching games with a simple double click.

I see thumbs down without a single good reason for not giving the users this feature.

Anyways, do whatever you want, but you are missing a great opportunity here.

**Comment by doZennn** [comment]
> I see thumbs down without a single good reason for not giving the users this feature.

My thumbs down is simply because i think it's out of scope. I don't think ULWGL should be used this way.

**Comment by Aqa-Ib** [comment]
Alright, but if you think that such a simple use case is out of scope, I can't call this software "Unified" in a literal way. It is "unified" just for GUI developers, that's it. Watching this situation, we will see forks arise for sure.

Regards.

**Comment by loathingKernel** [comment]
@Aqa-Ib since comments from three contributors to the project is not enough to convince you that there are issues doing this that you don't take into account, let me summarize some of them below for you and any future similar requests. We have explained this above but the discussion keeps going so let's do it again.

* It is out-of-scope, and if this was added it creates a precedent for similar out-of-scope requests.
* It will silently create the default directories required for ULWGL to run, which can be considered workspace pollution.
* It will fail silently without any output for users to report. The failure would probably be logged in `~/.xsession-errors`, systemd's journal or somewhere else depending on the DE the user uses. This will make it hard for new and not knowledgeable users to find the failure. From their standpoint the software "just doesn't work". It will require repeated back and forth to communicate where they will find the log of the failure, creating unnecessary noise.
* It requires hardcoding `GAMEID` to `0` which might work for most games but a few games will fail to even launch. This will contribute to the situation described above, where "for no reason" ULWGL "just doesn't work".
* We cannot just add message windows to inform the user, as ULWGL is predominantly meant to be used by other launchers which should be able to consume its output, and as such it should NOT interfere with them. Even the use of zenity progress dialogs was very carefully considered.

For these reasons and maybe more, this suggestion is not something we consider worth adding despite the convenience. It adds inconvenience for the rest of the use-cases. Hence the suggestion from the start that this should be handled by a thin wrapper around ULWGL that could offer said convenience to you or others who like to use it like you do.

**Comment by Aqa-Ib** [comment]
Fair enough.

**Comment by Aqa-Ib** [comment]
I am sorry if I annoyed you people, I was very passionate. 

Thank you loathingKernel for your reasons. While I don't agree, I respect the project members decision. I guess that this feature will be given by another project in the future for 'basic users' to enjoy.

Thank you all for the great work done and wish you the best. This project is an absolute revolution for playing on Linux.
