### ISSUE TITLE
Umu in lutris 0.5.17 lock to python 3.10+ and glibc 2.34+

### ISSUE THREAD

**Issue by kilolife** [Open-Wine-Components/ULWGL#91]
Umu in lutris 0.5.17 lock to python 3.10+ syntactically and hardlock to glibc 2.34+
As a result, umu does not work in ubuntu 20.04.

Python part: .local/share/lutris/runtime/umu/umu_plugins.py 173 line
"with" statement use new syntax from python 3.10+, however in Ubuntu 20.04 we have python 3.8

glibc part:
.local/share/lutris/runtime/umu/reaper: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by .local/share/lutris/runtime/umu/reaper)
#dpkg -l | grep libc-bin
ii libc-bin 2.31-0ubuntu9.14

**Comment by R1kaB3rN** [comment]
I suggest you make time to either update your distribution to the latest Ubuntu LTS, use the Lutris Flatpak, not use umu, or inform Lutris to add the POSIX script to account for old distributions.

Ubuntu LTS 22.04 satisfies the [minimum Mesa requirement for DXVK](https://github.com/doitsujin/dxvk/wiki/Driver-support), so you are bound to eventually run in gaming problems in the future or experience a subpar gaming experience. Moreover, umu currently tests against the latest Ubuntu LTS that's defined by Github in its CI.

To fix the glibc hardlock issue, please inform Lutris to compile reaper against a distribution with a lower glibc version.

**Comment by R1kaB3rN** [comment]
Closing because distribution cases like these can be decisively resolved by using the Lutris or umu Flatpak application, which would also satisfy your minimum Mesa requirements for DXVK. As a result, you will **not** run into a Python 3.10/ glibc lock issue in the future. However if you insist not to use the Flatpak, like I had suggested above, I suggest you make the time to update your distribution if gaming is of importance to you or to not use umu.
