### ISSUE TITLE
Launching a game with UMU via Lutris flatpak doesn't work if launched from Steam Deck gaming mode

### ISSUE THREAD

**Issue by pizzadude** [Open-Wine-Components/ULWGL#92]
Not sure where to report this, so I'll report it on both umu-launcher and lutris github.

If I try to launch a game that is installed via Lutris, (which I have switched the prefix to use GE-Proton (which uses umu) from previously Wine-GE)) in the Lutris flatpak, it works fine.

It even launches fine if ran as a non-steam game through Steam. (lutris flatpak with the game's id is added as non steam game, I used Boilr for this).

However, if I launch the game from gaming mode steam instead of desktop mode (on a Steam Deck), the game doesn't launch at all.

Switching the prefix back to Wine-GE, the problem goes away.

Any ideas?

**Comment by R1kaB3rN** [comment]
You risk breaking your Wine prefix after switching to Proton. However, putting aside whether the problem is with the prefix or not, you are bound to run into problems executing your games that way. The official way to use umu in Steam's gaming mode is to use the umu-launcher compatibility tool after adding your game as a non-steam game in the Steam client, not by executing the game via the Lutris Flatpak client which is added as a non-steam game.

But what's wrong with simply using Lutris on the Steam Deck to run the game? If Lutris doesn't support a gaming mode feature, I suggest you request that feature then wait until it's implemented. For now, look for another client besides Steam that supports gaming mode or install umu natively and use the umu-launcher tool in the Steam client.

**Comment by R1kaB3rN** [comment]
Also, in the near future, I plan to add native support for umu on the Steam Deck that won't require breaking the read-only seal which will be the preferred way to use it there. Because currently, the umu Flatpak is in an early state and isn't well tested. That way, users can run their games in gaming mode.

**Comment by pizzadude** [comment]
> You risk breaking your Wine prefix after switching to Proton.

Why, wasn't umu supposed to solve this?

> The official way to use umu in Steam's gaming mode is to use the umu-launcher compatibility tool after adding your game as a non-steam game in the Steam client, not by executing the game via the Lutris Flatpak client which is added as a non-steam game.

Then what's the point of integrating umu into Lutris which itself has a "add steam shortcut feature", replacing the already working Wine-GE and users get told "you're using it wrong". ?

**Comment by strycore** [comment]
You're not using anything wrong. umu should work in desktop mode, gaming mode and whatever other modes you want. It's meant as a way to reliably run Windows games on any Linux platform. 
You shouldn't use the "umu-launcher" compatibility mode in Steam, you should use what Lutris gives you and we have to make sure this works.

**Comment by GloriousEggroll** [comment]
> > You risk breaking your Wine prefix after switching to Proton.
> 
> Why, wasn't umu supposed to solve this?
> 
> > The official way to use umu in Steam's gaming mode is to use the umu-launcher compatibility tool after adding your game as a non-steam game in the Steam client, not by executing the game via the Lutris Flatpak client which is added as a non-steam game.
> 
> Then what's the point of integrating umu into Lutris which itself has a "add steam shortcut feature", replacing the already working Wine-GE and users get told "you're using it wrong". ?

lutris is a native linux application. as strider mentioned you should not use 'umu launcher' as a compatibility tool for it. once you have installed the game in lutris, either
1. add lutris as a non-steam application to steam WITHOUT any compatibility tool
or
2. use the "create steam shortcut" option on the game in lutris, again WITHOUT any compatibility tool

Lutris will handle using umu on it's own in the background.

As strider mentioned, you would not use proton on a native linux application, so why would you use umu-launcher?

There is a misunderstanding here of how the games are being launched.

When steam launches a windows game it goes
steam->internal scripts-> proton with pressure vessel

When steam launches a native linux non-steam game or application it goes
steam->directly to application

Lutris is the same for windows games:
lutris->umu-launcher->proton with pressure vessel

So, if you use the lutris "create steam shortcut" option it's adding lutris as a non-steam application to steam. It's still using lutris to launch the game. If you check the shortcut lutris creates it shows:

Target:
"/usr/bin/lutris"

Launch Options:
lutris:rungameid/4

And as you can see, it's using a lutris shortcut to run the game.

The only time you would use the "umu-launcher" compatibility tool is in order to use UMU directly on a windows game/application executable without lutris or any other launcher tools

**Comment by GloriousEggroll** [comment]
with the above being said if you've just used 'create a steam shortcut' via the lutris flatpak and that's it and are -not- trying to force any compatibility tool with it in steam then that should work.

**Comment by pizzadude** [comment]
>lutris is a native linux application. as strider mentioned you should not use 'umu launcher' as a compatibility tool for it. once you have installed the game in lutris, either add lutris as a non-steam application to steam WITHOUT any compatibility tool or use the "create steam shortcut" option on the game in lutris, again WITHOUT any compatibility tool

I never used any compatibility tool for Lutris. I know Lutris is a native linux application.

**Comment by pizzadude** [comment]
>with the above being said if you've just used 'create a steam shortcut' via the lutris flatpak and that's it and are -not- trying to force any compatibility tool with it in steam then that should work.

That's all I did. It doesn't work in gaming mode. Somebody else has the same issue here: https://github.com/lutris/lutris/issues/5436

**Comment by pizzadude** [comment]
@GloriousEggroll You seem to be misinterpreting me. I selected GE-Proton as the wine version WITHIN lutris. That makes the game, inside lutris, run with UMU. Then I created a steam shortcut with lutris. The game works fine in desktop mode and when run from lutris itself, but in gaming mode it doesn't launch at all. I did **not** select any compatibility tool in Steam.



> As strider mentioned, you would not use proton on a native linux application, so why would you use umu-launcher?

He was responding to [R1kaB3rN](https://github.com/R1kaB3rN) ( not me ), who suggested I use umu-launcher. I asked Strider via Discord to take a look at this issue (cuz we are friends), that's the reason he commented.

**Comment by GloriousEggroll** [comment]
> @GloriousEggroll You seem to be misinterpreting me. I selected GE-Proton as the wine version WITHIN lutris. That makes the game, inside lutris, run with UMU. Then I created a steam shortcut with lutris. The game works fine in desktop mode and when run from lutris itself, but in gaming mode it doesn't launch at all. I did **not** select any compatibility tool in Steam.
> 
> > As strider mentioned, you would not use proton on a native linux application, so why would you use umu-launcher?
> 
> He was responding to [R1kaB3rN](https://github.com/R1kaB3rN) ( not me ), who suggested I use umu-launcher. I asked Strider via Discord to take a look at this issue (cuz we are friends), that's the reason he commented.

Sorry for the confusion and thanks for clarification. I'm looking into reproducing the issue. Can you check in lutris if gamemode is off for the game and if not turn it off and let us know? Thanks

**Comment by pizzadude** [comment]
> Can you check in lutris if gamemode is off for the game and if not turn it off and let us know? Thanks

Hi, disabling gamemode within Lutris for that game doesn't solve the issue.

**Comment by GloriousEggroll** [comment]
I think I see what R1ka was referring to. In deck mode steam itself is already running inside a pressure-vessel container. Which means when lutris tries to run the game its trying to run pressure-vessel again inside an already running container.

**Comment by GloriousEggroll** [comment]
nvm thats not it either. i just verified steam still opens a separate pressure vessel instance if you launch a non-steam windows executable using proton as a compatibility tool, aka the same thing lutris would do. 

strider noted from the lutris bug tracker it might be a gamescope issue where $DISPLAY isnt being passed:
```
0124:err:winediag:nodrv_CreateWindow L"Make sure that your X server is running and that $DISPLAY is set correctly.
```

**Comment by R1kaB3rN** [comment]
After looking into it a bit, this only effects Steam Deck's gamescope session and using either the umu Flatpak or a Flatpak that uses umu in their runtime in it. Using either umu in a non-flatpak environment or the umu-launcher compatibility tool, users should not run into this issue.

This issue will need more digging and there'll need to be a way to gather/generate more logs from both gamescope and Flatpak to determine the precise cause. And hopefully, it's something in our control and doesn't require any workarounds

**Comment by R1kaB3rN** [comment]
Report of the upstream issue: https://github.com/ValveSoftware/gamescope/issues/1341

**Comment by pizzadude** [comment]
@R1kaB3rN @GloriousEggroll Hi, this is still an issue, even after Lutris just updated umu-launcher. Launching a game in steam deck gaming mode, with lutris flatpak and GE-Proton or Proton 9, ends up  with just a spinning steam logo with audio playing.

**Comment by rollercoaster** [comment]
> @R1kaB3rN @GloriousEggroll Hi, this is still an issue, even after Lutris just updated umu-launcher. Launching a game in steam deck gaming mode, with lutris flatpak and GE-Proton or Proton 9, ends up with just a spinning steam logo with audio playing.

Same

**Comment by AlmeidaRW** [comment]
I can reproduce the same behaviors too. Should this issue be re-opened or a new one to be created?

**Comment by MrArdillo** [comment]
I confirm that its still an issue on the last lutris version on jan 2025

**Comment by R1kaB3rN** [comment]
No, this is not an issue with umu-launcher but rather your client failing to meet the conditions for the game window to be brought to the foreground. Specifically for Lutris, it was a regression that happened just before version 0.5.18. More details on the cause, see https://github.com/lutris/lutris/issues/5436#issuecomment-2544028189. Their developers are already aware of this, so it’s just a matter of them pushing another release for their users then your distribution providing it. Though I expect that to probably be a while, they should at least update their Flatpak and I can try to get them to update it. No promises on that though. Alternatively, you can use another launcher such as Heroic Games Launcher which does not have this problem.

Additionally, in the Steam client, it will be a **hard requirement** that Steam’s shader cache is enabled. For more detail on that, see https://github.com/Open-Wine-Components/umu-launcher/issues/318#issuecomment-2567297982. Otherwise, users will still not have their game window brought to the foreground.

While it’s unfortunate that so many conditions and coordination have to be met for this to be solved, that’s just how it is for this specific problem due to 1) the issue not being addressed upstream in neither gamescope nor Steam 2) those clients continuing to depend on Steam for controller support rather than building their own or not using an existing solution like InputPlumber. For more context on that, see https://github.com/ShadowBlip/InputPlumber/issues/202.

And since users still make a lot of issues about this, I’ll be adding this to question to the project’s wiki. Any issues related to this and are invalid will be closed.
