### ISSUE TITLE
Proton-TkG doesn't run with umu-launcher both in lutris and with only umu-launcher

### ISSUE THREAD

**Issue by s0mebodyhelpme** [Open-Wine-Components/ULWGL#99]
When running with a proton build made with Frogging-Family's proton-tkg, the following is always displayed with both just umu-launcher and with the symlink method mentioned in #88  :

`wine: could not load ntdll.so: /home/al/.local/share/Steam/compatibilitytools.d/proton_tkg_experimental.bleeding.edge.9.0.94733.20240504/files/lib/ntdll.so: cannot open shared object file: No such file or directory`

in any game. however, it works with the latest GE-Proton given by lutris. upon inspection, though, it does seem that the file and folder structure are the same for both proton builds. how this occurs on TkG and not GE is odd to me.

Many thanks for the hard work on this project and consideration given to my issue, if any! and kindly feel free to ask for details if necessary!

**Comment by R1kaB3rN** [comment]
Actually, the folder structures are not the same because there isn't a wine subdirectory in the path you listed. Here's an example of GE-Proton's build of the to the ntdll.so file:

> ./GE-Proton9-4/files/lib/**wine**/i386-unix/ntdll.so
> ./GE-Proton9-4/files/lib64/**wine**/x86_64-unix/ntdll.so

Do all proton-tkg builds not contain that subdirectory?

**Comment by R1kaB3rN** [comment]
Also, do you know if Proton builds made with Frogging-Family's proton-tkg are specifically designed to run natively? If so, this is not supported and I don't really find it odd that you're experiencing issues as the proton-tkg's script and upstream's Makefile build Proton differently and have different expectations.

**Comment by loathingKernel** [comment]
> Also, do you know if Proton builds made with Frogging-Family's proton-tkg are specifically designed to run natively?

This is most likely the case indeed. I am looking through the build scripts of proton-tkg and all things point towards it being built outside of Steam Linux Runtime.

**Comment by s0mebodyhelpme** [comment]
@R1kaB3rN , it seems that my initial inspection was a bit off. Sorry. It turns out that, within the wine subidrectory of lib directory under files, the ntdll.so file exists within i386-unix, just like the latest GE Proton which works (at least my copy). Here are screenshots of the subdirectories for both Proton vesions for you to look at:

![05-05-2024+11:41:35](https://github.com/Open-Wine-Components/umu-launcher/assets/163645480/ab9f68e1-dfe0-4d82-b97c-be2ea58eda94)
![05-05-2024+11:41:40](https://github.com/Open-Wine-Components/umu-launcher/assets/163645480/ae08550b-5677-42cc-8001-ec8cfbc2f061)
![05-05-2024+11:42:06](https://github.com/Open-Wine-Components/umu-launcher/assets/163645480/98870c23-9712-4d1f-878b-4c4a7acdacbf)
![05-05-2024+11:42:13](https://github.com/Open-Wine-Components/umu-launcher/assets/163645480/2c18c485-35f7-4fa9-80c4-a1b44c0c2a82)

**Comment by R1kaB3rN** [comment]
Thanks for re-confirming the directory structure for me.

However, even if the directory structures are the same, the two Proton builds will be built differently. Examining the [proton-tkg build script](https://github.com/Frogging-Family/wine-tkg-git/blob/master/proton-tkg/proton-tkg.sh#L850), it will call run.sh then proceed to build Proton (wine) build against the Scout runtime as well as some of the host libraries instead of against the Sniper platform within a container. Using custom builds of Proton this way is not official, and will result in issues and differences when running inside Pressure Vessel. This will apply to Lutris or just any launcher that uses umu as its runtime, and this is [currently out of scope for this project because the goal is to run games the way Valve does using official builds](https://github.com/Open-Wine-Components/umu-launcher/issues/40#issuecomment-1962756681).

Therefore, I'll have to close this issue.

**Comment by R1kaB3rN** [comment]
In the future though, I might add a feature to allow not using Pressure Vessel. However, this feature would be strictly for debugging purposes, so any issues reported with that setting enabled will be closed instantly and users will be on their own.
